language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

cache:
    directories:
        - vendor

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

matrix:
    allow_failures:
        - php: nightly

sudo: false

script:
  - composer update $COMPOSER_PREFER
  - vendor/bin/atoum --test-ext
